print('{}\t{}'.format(self.getSensors(), self.getInputs()))
		self.mc.setMotor(0, 100)
		self.sc.engage()
		self.sc.setPosition(0)
		time.sleep(2)
		self.sc.setPosition(90)
		time.sleep(2)
		self.sc.setPosition(180)
		time.sleep(2)
